markdown: kramdown
highlighter: rouge
remote_theme: fongandrew/hydeout
sidebar_home_link:  true
baseurl: '/'

# Setup
title:            "Brendan Enrick's Blog"
tagline:          'All things tech considered here'
description:      "Brendan Enrick's Blog about all things tech."
url:              https://benrick.github.io
baseurl:          /

author:
  name:           'Brendan Enrick'
  url:            https://twitter.com/brendoneus

paginate: 5

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate

github:
  repo: https://github.com/benrick/benrick.github.io


twitter: "Brendoneus"
github: "DevChatter"
youtube: "c/DevChatter"
twitch: "DevChatter"
google_analytics: "UA-6547014-1"
disqus:
  shortname: brendanenrick
