# Dependencies
markdown:         redcarpet
highlighter:      pygments
remote_theme: poole/hyde

# Permalinks
#permalink:        pretty
#relative_permalinks: true

# Setup
title:            "Brendan Enrick's Blog"
tagline:          'All things tech considered here'
description:      "Brendan Enrick's Blog about all things tech."
url:              https://benrick.github.io
baseurl:          /

author:
  name:           'Brendan Enrick'
  url:            https://twitter.com/brendoneus

paginate:         5

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/benrick/benrick.github.io


twitter: "Brendoneus"
github: "DevChatter"
youtube: "c/DevChatter"
twitch: "DevChatter"
google_analytics: "UA-6547014-1"
