markdown: kramdown
highlighter: rouge
remote_theme: fongandrew/hydeout
sidebar_home_link:  true
baseurl: '/'

# Setup
title:            "Brendan Enrick's Blog"
tagline:          'All things tech considered here'
description:      "Brendan Enrick's Blog about all things tech."
url:              https://brendoneus.com/
baseurl:          /

author:
  name:           'Brendan Enrick'
  url:            https://twitter.com/brendoneus

paginate: 5

plugins:
  - jekyll-redirect-from
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-seo-tag

github:
  repo: https://github.com/benrick/benrick.github.io

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      show_ads: true

twitter: "Brendoneus"
github: "DevChatter"
youtube: "c/DevChatter"
twitch: "DevChatter"
google_analytics: "UA-6547014-1"
google_adsense_client: "ca-pub-2042163838320812"
disqus:
  shortname: brendanenrick
