name: Daily Refresh

on:
  schedule:
    - cron:  '0 6 * * *' # Runs every day at 6am

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  refresh:
    runs-on: ubuntu-latest
    
    steps:
      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!
        
      - name: Run a multi-line script
        run: |
          curl --fail --request POST \
            --url https://api.github.com/repos/benrick/benrick.github.io/pages/builds
            --header "Authorization: Bearer $USER_TOKEN"
        env:
          USER_TOKEN: ${{secrets.USER_TOKEN}}
