name: Daily Refresh

on:
  schedule:
    - cron:  '0 10 * * *' # Runs every day at 6am
    - cron:  '1 4 * * *' # Runs every day at 12:01am

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  refresh:
    runs-on: ubuntu-latest
    
    steps:     
      - name: Refresh Build From curl
        run: |
          curl --fail --request POST \
            --url https://api.github.com/repos/${{ github.repository }}/pages/builds \
            --header "Authorization: Bearer $USER_TOKEN"
        env:
          USER_TOKEN: ${{secrets.USER_TOKEN}}
